### ISSUE TITLE
App Configuration (Repository, Themes, Title...)

### ISSUE THREAD

**Issue by oblomov-dev** [oblomov-dev/abap2UI5#129]
Issue to find a good place for the app configuration.

First solution (which can be improved in the future) - you configure it with the first call of the index.html:
<img width="786" alt="image" src="https://user-images.githubusercontent.com/102328295/228290000-42c77c96-9adb-4a6a-8a97-9fcda973b851.png">

Then an user can call abap2UI5 for instance like this:
```abap
  CASE lv_system.
      WHEN 'PROD'.
        lv_ui5_path = 'resources/sap-ui-core.js'.
        lv_theme    = 'sap_horizon'.
      WHEN 'Q'.
        lv_ui5_path = 'resources/sap-ui-core.js'.
        lv_theme    = 'sap_horizon'.
      WHEN 'DEV'.
        lv_ui5_path = 'https://ui5.sap.com/resources/sap-ui-core.js'.
        lv_theme    = 'sap_horizon'.
    ENDCASE.

    DATA(lv_resp) = SWITCH #( request->get_method( )
       WHEN 'GET'
        THEN z2ui5_cl_http_handler=>main_index_html(
                    library_path = lv_ui5_path
                    theme        = lv_theme 
                    )
       WHEN 'POST' THEN z2ui5_cl_http_handler=>main_roundtrip( ) ).
```

Idea:
(1) configuration can be set during runtime in the http handler by the user
(2) if needed, users can also create a customizing table to set the theme etc.
(3) optional, when different apps need different themes you can also create additional http handler and call from the outside the theme you want (think this is also the old its mobile idea where you decide which theming and html templates are used by changing the http handler)
(4) abap2ui5 stays small and simple -> configuration is outside and not a part of abap2ui5

The app itself (z2ui5_if_app) has no own configuration. Due to the fact that abap2ui5 apps can call each other and switching between them is a part of the concept, it makes no sense to change the theme or ui5_path between two apps. Example:
https://twitter.com/OblomovDev/status/1640743794206228480

In addition you have the chance to copy&paste apps between systems without changing the configuration.

This is just the actual solution, feel free to share your ideas or experiences, that we can find out if the place is good or there is a better one.

**Comment by mbtools** [comment]
For everyone's reference, here's the config doc for on-prem:

![image](https://user-images.githubusercontent.com/59966492/228327805-c1fcbe79-5303-4b59-83d6-d9104f6ebb0f.png)

**Comment by oblomov-dev** [comment]
SAPGUI - what a beauty 😍

Thank you a lot for the picture (have no on-premise so i can't check by myself)!
Then the on-premise user have the possibility to read this customizing table in their http handler and call abap2UI5 with the right bootstrap entry. So every abap2UI5 app will be called with the same configuration than any other UI5 app in the system - that sounds good to me! 👍 
Steampunk users would maybe just use their ui5 cloud cdn and give it into abap2UI5.

**Comment by oblomov-dev** [comment]
Added the picture and a short guidance to the abap2UI5 wiki:
https://github.com/oblomov-dev/abap2ui5/wiki/Configuration

I will close the issue now. If any of you find out a better position, feel free to reopen the issue or create a new one. Difficult topic and this is just the current status, we can change it in the future.
