### ISSUE TITLE
Diffs for on-prem

### ISSUE THREAD

**Issue by mbtools** [oblomov-dev/abap2UI5#133]
There are minor diffs when pulling (main or _dev) into a on-prem system (7.54 ABAP Dev Edition):

![image](https://user-images.githubusercontent.com/59966492/228943355-f1bec8f4-a7e8-4b36-937d-6b18746afd78.png)

The ABAP language version can't be avoided until we solve https://github.com/abapGit/abapGit/issues/6154.

The package xml is missing the BOM mark. I can open a PR with the correct file if you like.

**Comment by oblomov-dev** [comment]
Oh yes a PR would be a great help! I am flying blind with on-prem compatibility at the moment, only have a steampunk system and unfortunately can not test on-prem by myself.

Updated last week the draft table and package description, i guess with this i put in these changes by mistake. When you open a PR and i merge it, i try to take care to only update the source code artifacts from steampunk (adt-git) in the future. Would be nice when normal on-prem users get no diffs when they install abap2ui5 with abapgit.
