### ISSUE TITLE
Hi. I have some question for education(?).

### ISSUE THREAD

**Issue by yroomoo** [oblomov-dev/abap2UI5#142]
Dear. ABAP2UI5 Team.

Hi. Thank you for creating the ABAP2UI5.
I`m ABAP Developer from South Korea.

I was moved by the ABAP2UI5.
So, I want learn more about the ABAP2UI5 and Share experience throught my blog(For Free).
Would you mind if I do these activities?

Sincerely.
yroomoo.

**Comment by oblomov-dev** [comment]
Hi yroomoo,

nice to hear from you and thank you for trying abap2UI5 out. That is a great idea! Feel free to share your experiences on your blog. abap2UI5 is an open-source project, and any effort to increase its popularity within the ABAP community is greatly appreciated. Also positiv/negative feedback is welcome, so if you get in trouble with trying something out, don't hesitate to open an issue for that, that we can try to learn from you experiences and try to make it better.

Best regards!

**Comment by oblomov-dev** [comment]
Hi yroomoo,
i close the issue, if you have further questions, just open a new one.
Best regards.
