### ISSUE TITLE
my pain points / feedback

### ISSUE THREAD

**Issue by nomssi** [oblomov-dev/abap2UI5#144]
First of all, thanks to @oblomov-dev for a great tool.

Something I hope to see documented in the upcomming blog (Technical documentation):

abap2UI5 is stateless, but it creates a powerful illusion of state with it draft table magic. This works well most of the time, but the developer must actively help to maintain this illusion if the code has object references. 

a) make sure all objects (including their attributes that are object reference) implement the IF_SERIALIZABLE_OBJECT tag interface
b) beware the comparison of objects, as two objects with the same attributes are equivalent. Comparisons like    

    IF oref1 = oref2.
        ...
    ENDIF.

eventually fail after one object is serialized and deserialized and the other is not. This may happen if one of the object references is an attribute in another object. I am now using something like
    
    IF oref2 IS BOUND AND oref1->key = oref2->key.
        ...
    ENDIF.

to avoid the subtle errors in a legacy logic where I was using singletons created in class constructor once (singletons are global variables :( ) 

abap2UI5 is simple to use, I can easily created Popup to input. But while doing so I was tempted to simulate synchronous input , where the code awaits the result and the resume.  Like when you execute a dynpro with CALL SCREEN. This is not possible (yet ?). I have been mulling about using the ABAP promises https://github.com/abapify/promise to achieve this control flow.

That is all for now

**Comment by oblomov-dev** [comment]
Hi nomssi,

thanks for trying abap2UI5 out (you are one if the first 👏) and all the pull requests with the corrections during this time!

**serialization**
You summed up the situation very well i think. serialization can be very powerful and like magic but when you don't know what you do it also can end in very bad situations and problems which are hard to manage.
i had in mind just to use it for interim results like an input field or some edited entries in a table. it is very helpful that you don't have to create an extra db table for this. when you only use it to serialize your ui values and use the app class only for ui logic and do the other things in other (not serializable) class you will not run into problems.
But: of course you also have the possibility to serialize your whole logic and every class and try to simulate a session. abap2ui5 makes no restriction, but then it is up to the abap developer if it will work or end in the reference problems you talk about. serialization is nice but definitely more an abap expert topic. it is a good idea to clarify that in the "technical backgrounds" of the blog series, that no one has wrong expectations and is aware of this!

**popups**
abap2ui5 works all the time with a server roundtrip so the flow logic is: frontend -> server roundtrip -> frontend -> server roundtrip etc. you can not break out of this.
but i am not sure if i understand you right. can you give me more information or describe an example?
you want to do something asynchronously? or you want to do something on the frontend while you executed an action in the backend (and dont want to wait fo the result)?

Best regards

**Comment by oblomov-dev** [comment]
P.S.: made some bigger changes, flow logic is slightly different now, hope you can refactor your apps without too big effort. all examples are updated that you can see how it works. also needed to adjust the methods "set_app_client" and "trans_ref_tab_2_tab" where you did a lot of work, hope it is still running on your release!

**Comment by nomssi** [comment]
Hi Oblomov,

about popups:  the concrete use case is implementing an input port. I am trying to implement a synchronous input/prompt where the code waits for the user to input data that will be processed. The current popups work well asynchronously, but I am trying to simulate a modal input dialog. 

    DATA my_variable TYPE string.
    DO.
        CLEAR my_variable.
        prompt the user to input data (e.g. in a popup)
        wait for the user to confirm the entry, transfer the data to my_variable.
       use my_variable in my custom logic.
    ENDDO.

Without the external DO / ENDDO loop, I would be able to simulate this with event handling.
With the loop, I am frankly not sure it this can be done in a REST environment.

Best regards

P.S. your nickname seems to mean a sloth. If then, how come an Oblomov can be so productive?

**Comment by oblomov-dev** [comment]
yes
do. 
... 
enddo. 
structures are not possible with abap2UI5. After every request the sessions is terminated and this means also that the complete call stack is deleted. the program in a way restarts again with every request.

for your use case:
yes, simulating it with event handling is the only option. you can save in a variable if the popup is active or not. And if yes let the app display again and agin the popup till the user made the correct input. for better readability you can think of encapsulating the popup in an own app. i made some examples here: z2ui5_cl_app_demo_12 
popups and a good control flow with it is not easy but an important topic, so let me know if you have further use cases that we can check how they are realizable with abap2UI5.

best regards.

P.S.: yes also good question, the idea was finding a "lazy" way to create ui5 apps with minimum effort, but i forgot that the framework author has then more work to do 😂 maybe i should rethink the animal again ;)
