### ISSUE TITLE
Language \ Locale

### ISSUE THREAD

**Issue by choper725** [oblomov-dev/abap2UI5#148]
how can we change ui locale from abap code ? or rather set it that way..

any thoughts on making it globaly changeable ?

**Comment by oblomov-dev** [comment]
hi choper, i am not sure if i understand what you want to do...

Do you want to read the browser language? Or change something?

when it is set with the parameter "sap-ui-language" you can read it with the if_z2ui5_client->get( ) 
sy-langu should have the login language

**Comment by choper725** [comment]
ill try to elaborate, how do i make an app with specific language other than english, without changing the url for it ?

**Comment by oblomov-dev** [comment]
The language handling works similar to selections-screens or screen pbo/pai development. abap2ui5 is completly in the backend, there is now i18n etc.

so when you create views and use texts don't put them directly into the attributes (like it is in the demos), use T100 messages or text pool messages instead.

**Comment by choper725** [comment]
i see, maybe the proper term i need is RTL support of the entire app and components, maybe what i was taking about was the parameter sap-ui-language, how do i set it ? in the main_index_html method ?

**Comment by oblomov-dev** [comment]
when you don't want to set it with the url then it is possible with the index.html. I updated the interface of the method for that, now you can also import the paramter "rtl". 

<img width="727" alt="image" src="https://user-images.githubusercontent.com/102328295/231158043-3ccd3c66-cdc8-4c01-b90e-d6720ebe6b95.png">

i tried it and it seems to work:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/102328295/231158142-733a3b56-688e-4adb-9d21-4bcb979010e3.png">
<img width="500" alt="image" src="https://user-images.githubusercontent.com/102328295/231158313-01b515cf-7cb5-444e-b795-e84d11cf6a3a.png">

**Comment by choper725** [comment]
that does the trick, but until i dont change the sap-ui-language parameter in the constructor all the localization of certain controls, such as date picker, is in english (months and so on..)

**Comment by oblomov-dev** [comment]
abap2ui5 should behave like a normal ui5 app. because it is a normal ui5 index.html

i checked it and without url parameter it uses the default language of my browser. is maybe your default browser language english?

when i change it with an url paramter it switches to the language of the url parameter, tested it with the date control and the name of the month is then in the certain language.

**Comment by choper725** [comment]
thats right, the browser is in En
im changing it via, data-sap-ui-language parameter on the main_index to AR, hardcoded, this does the trick, btw this enables RTL also

**Comment by choper725** [comment]
yeah, i know it will overwrite, maybe it is a good idea getting it out as a string to the contructor

**Comment by choper725** [comment]
there is a duplicate in sap-ui-theme, maybe one of them should be language ?

**Comment by oblomov-dev** [comment]
ah thank you i fix it!

**Comment by oblomov-dev** [comment]
commited, should be all there nowl

**Comment by choper725** [comment]
wasnt “data-sap-ui-language” should be there? or i was wrong thinking so..?

**Comment by oblomov-dev** [comment]
i left it away (like before) because as default i think the language of the browser should be used. when i overwrite it per default with english it could be confusing for a lot of people.
