### ISSUE TITLE
Hi. Where can i find 'z2ui5_cl_xml_view_helper' Class?

### ISSUE THREAD

**Issue by yroomoo** [oblomov-dev/abap2UI5#153]
Hi.

bc, my server can`t use ABAPGit.
So I install ABAP2UI5 manually.
create class, source copy & paste.

In some demo apps, i found 'z2ui5_cl_xml_view_helper' class was used.
but, i can`t found source code about 'z2ui5_cl_xml_view_helper'.
where can i find it ?

**Comment by larshp** [comment]
abapGit can also upload/download zip files, see https://docs.abapgit.org/guide-offline-install.html

but to answer the question, its at https://github.com/oblomov-dev/abap2UI5/blob/main/src/00/z2ui5_cl_xml_view_helper.clas.abap

**Comment by yroomoo** [comment]
> abapGit can also upload/download zip files, see https://docs.abapgit.org/guide-offline-install.html
> 
> but to answer the question, its at https://github.com/oblomov-dev/abap2UI5/blob/main/src/00/z2ui5_cl_xml_view_helper.clas.abap

I found it. Thank you :)

**Comment by oblomov-dev** [comment]
yes i changed the structure of abap2UI5 a little bit and separated the view creation from the rest. using the view helper is now optional and therefore also in the demo folder. thanks for the help @larshp . i close the issue now.
