### ISSUE TITLE
Type "ABAP_BOOLEAN" is unknown in NW 752 SP04

### ISSUE THREAD

**Issue by christianguenter2** [oblomov-dev/abap2UI5#155]
![grafik](https://user-images.githubusercontent.com/17437789/231087026-239825bc-41c3-4c8b-b154-94051865a258.png)

**Comment by oblomov-dev** [comment]
huh accidentally used boolean instead of bool, fixed it. change is in the main branch now. thank you for the hint!

**Comment by christianguenter2** [comment]
Thx. Works.
