### ISSUE TITLE
A generic reference cannot be dereferenced (->) in the current statement.

### ISSUE THREAD

**Issue by christianguenter2** [oblomov-dev/abap2UI5#156]
Syntax errors in NW 752 SP04
![grafik](https://user-images.githubusercontent.com/17437789/231087658-4c7df259-d65f-493c-a525-d0386c680313.png)

**Comment by oblomov-dev** [comment]
Thanks for the issue, i can not test with 752 by myself. i fixed the issues and use an extra field symbol now, i hope it is compatible with that. changes are in the main branch, you can try again.

**Comment by christianguenter2** [comment]
Thx. Still one left:
![grafik](https://user-images.githubusercontent.com/17437789/231112373-5465724a-284b-4e99-a77e-b41bef766e63.png)

Shouldn't this be caught by 
https://github.com/oblomov-dev/abap2UI5/blob/d80f0900de87bc74dc35680f6bb3b91ba7c68f9b/abaplint.jsonc#L13
? CC @larshp

**Comment by larshp** [comment]
there is a bug in the linter

**Comment by oblomov-dev** [comment]
fixed it again and updated main.
