### ISSUE TITLE
Outdated bootstrapping documentation

### ISSUE THREAD

**Issue by christianguenter2** [oblomov-dev/abap2UI5#169]
This documentation seems outdated
https://github.com/oblomov-dev/abap2ui5/wiki/Configuration

Should be something like:
```abap
    DATA(lt_config) = VALUE z2ui5_if_client=>ty_t_name_value(
      ( name = `data-sap-ui-theme`         value = `sap_belize` ) " <= adjusted
      ( name = `src`                       value = `https://sdk.openui5.org/resources/sap-ui-core.js` ) " <= adjusted
      ( name = `data-sap-ui-libs`          value = `sap.m` )
      ( name = `data-sap-ui-bindingSyntax` value = `complex` )
      ( name = `data-sap-ui-frameOptions`  value = `trusted` )
      ( name = `data-sap-ui-compatVersion` value = `edge` ) ).

    DATA(lv_resp) = SWITCH #( server->request->get_method( )
       WHEN 'GET'  THEN z2ui5_cl_http_handler=>main_index_html(
                          title    = `abap2UI5`
                          t_config = lt_config )
       WHEN 'POST' THEN z2ui5_cl_http_handler=>main_roundtrip( ) ).

```

**Comment by choper725** [comment]
lt config not mandatory if you dont want to modify it..

**Comment by christianguenter2** [comment]
Yeah, I know. But if I want to modify it, it would be nice if the code examples in the documentation are up to date :-)

**Comment by christianguenter2** [comment]
#148

**Comment by oblomov-dev** [comment]
yes everything changes very fast at the moment :) i do at the moment an extra blog post for this, that the most important information is collected at one place.

**Comment by oblomov-dev** [comment]
updated everything, here is the new documentation:
https://blogs.sap.com/2023/04/14/abap2ui5-6-7-installation-configuration-debugging/

**Comment by choper725** [comment]
i think, the refer to the firat blog post in there is outdated also, could be ?

**Comment by oblomov-dev** [comment]
corrected again the links. is there still something not working?

**Comment by choper725** [comment]
the code snippet in blog 1 for z2ui5_cl_app_demo_01 is different and the interface implementation code snippet is wrong also, no? 
that is confusing that the doca referencing wrong code

**Comment by oblomov-dev** [comment]
ah yes thanks corrected it!

**Comment by oblomov-dev** [comment]
i close this issue, just open a new one if you find outdated documentation.
