### ISSUE TITLE
Wiki Link 

### ISSUE THREAD

**Issue by thomasmarkert** [oblomov-dev/abap2UI5#175]
Hello,

the wiki link does not work.
https://github.com/oblomov-dev/ABAP2UI5/wiki

Best Regards 
Thomas

**Comment by oblomov-dev** [comment]
i deleted the wiki and collected all information now in one place (blog series), also updated all links.

**Comment by oblomov-dev** [comment]
i close this isse, just reopen or create a new issue if you find dead links.
