### ISSUE TITLE
DEMO 21: Popup to select

### ISSUE THREAD

**Issue by nomssi** [oblomov-dev/abap2UI5#176]
If I press "continue" without selecting any entry, I get an exception.

Proposed fix in class Z2UI5_CL_APP_DEMO_21

          WHEN 'POPUP_TABLE_CONTINUE'.
            DELETE t_tab WHERE selkz = abap_false.
            "client->popup_message_toast( `Entry selected: ` && t_tab[ 1 ]-title ).
            client->popup_message_toast( `Entry selected: ` && VALUE #( t_tab[ 1 ]-title DEFAULT `no entry selected` )  ).

**Comment by oblomov-dev** [comment]
thank you, fixed it.
