### ISSUE TITLE
"Cannot convert character set"

### ISSUE THREAD

**Issue by TopperDEL** [oblomov-dev/abap2UI5#183]
I'm new to abapGIT and abap2UI5. I just installed abapGIT and tried to install abap2UI5 via a offline package, but I get the following error:
![image](https://user-images.githubusercontent.com/1833242/232475975-4568d344-1f22-4710-b743-7795468339ab.png)

The system does not seem to be up to dat, but from my understanding at least the main_v702-branch should be supported:
![image](https://user-images.githubusercontent.com/1833242/232476234-4403cb04-82b9-4fda-8a26-ad406d5d298e.png)

Any ideas what could be wrong/missing here?

**Comment by larshp** [comment]
is it a unicode system?

**Comment by TopperDEL** [comment]
Oh! Just found out it is not!
Is this a show-stopper?

**Comment by larshp** [comment]
it should not be, its not often we get to test abapGit in a non-unicode system, guess there is a bug somewhere in the codepage conversion logic in abapGit

**Comment by TopperDEL** [comment]
Can you give me a hint where that logic is? I may do some searching/debugging.

**Comment by TopperDEL** [comment]
Thanks!

A quick and dirty hack did it for the moment:
![image](https://user-images.githubusercontent.com/1833242/232486810-343ad4ce-2115-43e4-aea5-1f3f74e0d0f3.png)

But there are more errors coming up with my SAP-version here, so this might lead to nothing. I might have to bring that system to a newer relase before it makes any sense to continue.

**Comment by mbtools** [comment]
https://github.com/abapGit/abapGit/pull/6237 should fix this issue
