### ISSUE TITLE
Extension UI Element 

### ISSUE THREAD

**Issue by thomasmarkert** [oblomov-dev/abap2UI5#184]
Hey,

Would it be possible to add the "navigated" attribute to the StandardListentem ui element?

`<StandardListItem
				type="Active"
				title="{Name}"
				navigated="{
					parts: [
						'settings>/navigatedItem',
						'ProductId'
					],
					formatter: '.isNavigated'
				}"
				press="onPress" />`

Best Regards
Thomas

**Comment by oblomov-dev** [comment]
I gave it a quick look, but so far it looks that there is a javascript function needed to handle the navigated attribute. but i did not completely understand the use case. can you explain what you want to do or why you need this attribute?

**Comment by thomasmarkert** [comment]
I'm looking for a simple way similar to the ListReport that I can create using ABAP2UI5.(Overview with branching into detail)

**Comment by choper725** [comment]
can the same logic be possible via Table ?

**Comment by oblomov-dev** [comment]
Yes list and table are based on the same control. You just need to add the selectionchange event like I did with the list to the table. 

If you do it feel free to open a PR then I can add it to main. Otherwise I will change it tomorrow.

**Comment by oblomov-dev** [comment]
see https://github.com/oblomov-dev/abap2UI5/issues/208
