### ISSUE TITLE
Syntac Error in Class ZCL_ABAP2UI5

### ISSUE THREAD

**Issue by thomasmarkert** [oblomov-dev/abap2UI5#187]
Hey,

After importing the Repository with ZABAPGIT_STANDALONE I get for the class ZCL_ABAP2UI5
following error:

![image](https://user-images.githubusercontent.com/123086939/232676644-24cede38-a4f5-427b-acf7-142724e01aa0.png)

Best Regards
Thomas

**Comment by oblomov-dev** [comment]
Yes I had to make yesterday some refactoring and renamed the methods. Change the method calls to http_get and http_post. Or copy the updated snipped from the documentation.

**Comment by thomasmarkert** [comment]
Great. It works. 
👍😊
