### ISSUE TITLE
Json deserialization issue

### ISSUE THREAD

**Issue by tienlevan** [oblomov-dev/abap2UI5#189]
Today, I tried out abap2ui5 on my premise system but when i started any demo app  i got a dump as the image:
![image](https://user-images.githubusercontent.com/44895008/232841283-373c9f85-e288-4c7d-82fe-7c98b95ae0d5.png)

Please help me!

**Comment by oblomov-dev** [comment]
HI tienlevan,
thanks for sharing the issue!
can you see the starting page? and/or demo overview page?
It looks like a dump, can you send me a screenshot of the dump in st22 or in eclipse, that i can see the code line where it is raised.

**Comment by tienlevan** [comment]
Hi @oblomov-dev ,
On the starting page, I clicked on button continue to show demo app, the dump was raised in class /UI2/CL_JSON method Restore:
![image](https://user-images.githubusercontent.com/44895008/232948901-8763140e-0148-4937-8848-559282ca37c3.png).
![image](https://user-images.githubusercontent.com/44895008/232949330-4af0789f-92a5-4975-a0d9-cfdd0d8a0e5a.png)

**Comment by oblomov-dev** [comment]
can you try to start an app directly by using for example the following classname 'z2ui5_cl_app_demo_01' at the starting page and go to the app via link?

Can you also send me a screenshot of the callstack that i can see which method of the frameworks caused the problem.

So far it seems like a very generic problem and i do not get it on my system 🤔

**Comment by tienlevan** [comment]
Hi @oblomov-dev,

I have solved the dump by myself! The Problem came from generic type in json deserialization method!
Thanks you for supporting me!

**Comment by choper725** [comment]
it will help others if you write how you solved it.
