### ISSUE TITLE
StandardListItemInfoStateInverted 

### ISSUE THREAD

**Issue by thomasmarkert** [oblomov-dev/abap2UI5#191]
Hey,

I want to implement the following list:

StandardListItemInfoStateInverted
https://sapui5.hana.ondemand.com/#/entity/sap.m.StandardListItem/sample/sap.m.sample.StandardListItemWrapping

StandardListItemWrapping
https://sapui5.hana.ondemand.com/#/entity/sap.m.StandardListItem/sample/sap.m.sample.StandardListItemInfoStateInverted

My Code StandardListItemInfoStateInverted

...
      t_tab = VALUE #(
        ( title = 'Peter'   info = 'Information'    descr = 'this is a description' icon = 'sap-icon://badge'      highlight = 'Information' )
        ( title = 'Peter1'  info = 'Success'        descr = 'this is a description1' icon = 'sap-icon://favorite'   highlight = 'Success')
        ( title = 'Peter2'  info = 'Warning'        descr = 'this is a description2' icon = 'sap-icon://employee'   highlight = 'Warning')
        ( title = 'Peter3'  info = 'Error'          descr = 'this is a description3' icon = 'sap-icon://accept'     highlight = 'Error' )
        ( title = 'Peter4'  info = 'None'           descr = 'this is a description4' icon = 'sap-icon://activities' highlight = 'None')
        ( title = 'Peter5'  info = 'Information'    descr = 'this is a description5' icon = 'sap-icon://account'    highlight = 'Information' )
      ).
...
    page->list(
        headertext      = 'List Ouput'
        items           = client->_bind( t_tab )
        mode            = `None`
    )->_generic(
        name = `StandardListItemInfoStateInverted`
        t_prop = VALUE #(
            ( n = `title`       v = '{TITLE}' )
            ( n = `description` v = '{DESCR}' )
            ( n = `icon`        v = '{ICON}' )
            ( n = `info`        v = '{INFO}' )
            ( n = `iconInset`   v = 'false' )
            ( n = `iconState`   v = '{highlight}' )
            ( n = `infoStateInverted`   v = 'true' )
            ( n = `highlight`   v = '{highlight}' )
       )

Unfortunately I get the following error:

5loader-dbg.js:1180 Uncaught (in promise) ModuleError: failed to load 'sap/m/StandardListItemInfoStateInverted.js' from https://sdk.openui5.org/resources/sap/m/StandardListItemInfoStateInverted.js: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://sdk.openui5.org/resources/sap/m/StandardListItemInfoStateInverted.js'.
    at ve (https://sdk.openui5.org/resources/sap-ui-core.js:10:7732)
    at de.failWith (https://sdk.openui5.org/resources/sap-ui-core.js:10:5570)
    at Le (https://sdk.openui5.org/resources/sap-ui-core.js:10:14352)
    at Ie (https://sdk.openui5.org/resources/sap-ui-core.js:10:16322)
 

Best Regards
Thomas

**Comment by oblomov-dev** [comment]
The error message says that the control 'sap/m/StandardListItemInfoStateInverted.js' can not be found or does not exist.
The reason is that you accidentally used 'StandardListItemInfoStateInverted' instead of 'StandardListItem'. So just use 'StandardListItem' for the name of generic.
additionally i think you forget to use the control items after the list. Check this again:
<img width="611" alt="image" src="https://user-images.githubusercontent.com/102328295/233321185-9e819128-eef6-468a-821e-f1466c6f9134.png">

**Comment by thomasmarkert** [comment]
Hey
this is my  page

![image](https://user-images.githubusercontent.com/123086939/233352441-92f1868e-cfe2-4f8b-8949-0320606dcfdd.png)

this is the sapui5 page

![image](https://user-images.githubusercontent.com/123086939/233352584-2464ef78-711b-4159-9887-3e314d5b5218.png)

Why can't I see any colors?

My Code
`   IF check_initialized = abap_false.
      check_initialized = abap_true.

      t_tab = VALUE #(
        ( title = 'Peter'   info = 'Information'    descr = 'this is a description' icon = 'sap-icon://badge'      highlight = 'Information' )
        ( title = 'Peter1'  info = 'Success'        descr = 'this is a description1' icon = 'sap-icon://favorite'   highlight = 'Success')
        ( title = 'Peter2'  info = 'Warning'        descr = 'this is a description2' icon = 'sap-icon://employee'   highlight = 'Warning')
        ( title = 'Peter3'  info = 'Error'          descr = 'this is a description3' icon = 'sap-icon://accept'     highlight = 'Error' )
        ( title = 'Peter4'  info = 'None'           descr = 'this is a description4' icon = 'sap-icon://activities' highlight = 'None')
        ( title = 'Peter5'  info = 'Information'    descr = 'this is a description5' icon = 'sap-icon://account'    highlight = 'Information' )
      ).

    ENDIF.

    CASE client->get( )-event.
      When 'TEST'.
        client->popup_message_box( `Test` ).

      WHEN 'SELCHANGE'.
        DATA(lt_sel) = t_tab.
        DELETE lt_sel WHERE selected = abap_false.
        client->popup_message_box( `go to details for item ` && lt_sel[ 1 ]-title ).


      WHEN 'BACK'.
        client->nav_app_leave( client->get_app( client->get( )-id_prev_app_stack ) ).
    ENDCASE.

    DATA(page) = z2ui5_cl_xml_view=>factory( )->shell(
        )->page(
            title          = 'abap2UI5 - List'
            navbuttonpress = client->_event( 'BACK' )
              shownavbutton = abap_true
            )->header_content(
                )->link(
                    text = 'Source_Code'  target = '_blank'
                    href = z2ui5_cl_xml_view=>hlp_get_source_code_url( app = me get = client->get( ) )
            )->get_parent( ).

    page->list(
        headertext      = 'List Ouput'
        items           = client->_bind( t_tab )
        mode            = `SingleSelectMaster`
        selectionchange = client->_event( 'SELCHANGE' )
    )->_generic(
         name = `StandardListItem`
            t_prop = VALUE #(
                ( n = `title`       v = '{TITLE}' )
                ( n = `description` v = '{DESCR}' )
                ( n = `icon`        v = '{ICON}' )
                ( n = `iconInset`   v = 'false' )
                ( n = `highlight`   v = '{highlight}' )
                ( n = `info`        v = '{INFO}' )
                ( n = `infoState`   v = '{highlight}' )
                ( n = `infoStateInverted`   v = 'true' )
                ( n = 'type'      v = `Navigation` )
                ( n = 'selected'    v = `{SELECTED}` )
                ) ).

    client->set_next( VALUE #( xml_main = page->get_root(  )->xml_get( ) ) ).`
