### ISSUE TITLE
Syntax error in unit test

### ISSUE THREAD

**Issue by nomssi** [oblomov-dev/abap2UI5#200]
In unit test method  TEST_APP_DEEP_DATA( ) of class Z2UI5_CL_HTTP_HANDLER, the field symbol <row> must be defined as

       FIELD-SYMBOLS <row> TYPE REF TO data.

on lower releases, or a syntax error occurs.

**Comment by larshp** [comment]
guess https://github.com/oblomov-dev/abap2UI5/blob/main/src/z2ui5_cl_http_handler.clas.testclasses.abap#L783

**Comment by oblomov-dev** [comment]
ah interesting, fixed now:
<img width="488" alt="image" src="https://user-images.githubusercontent.com/102328295/235065034-9ae41c74-779a-454d-9077-538c8ff1903d.png">
