### ISSUE TITLE
Curr data type TwoWay binding not working

### ISSUE THREAD

**Issue by RiTo0000** [oblomov-dev/abap2UI5#203]
Hi what data type should I use for decimal numbers ? 

I have input field for price and when i use curr as data type value is not transferred to the variable.  I tried other data types and it seems like only decimal numbers have an issue. When I use char or int it works fine. 

Please help

**Comment by oblomov-dev** [comment]
Hi,

there was a bug that type P was not transported. I fixed it.
Now it should work, check: z2ui5_cl_app_demo_47

**Comment by nomssi** [comment]
when I enter a negative value in the demo,  something bad happens

**Comment by oblomov-dev** [comment]
Fixed it again, now the conversion should work better:
<img width="1301" alt="Bildschirm­foto 2023-05-01 um 22 38 41" src="https://user-images.githubusercontent.com/102328295/235527077-fb6dced9-dc5d-4bf5-8b62-23acacdbae80.png">

**Comment by RiTo0000** [comment]
Hi, 

the issue is fixed it works great now. Thank you very much
