### ISSUE TITLE
Change the Font-size or Height

### ISSUE THREAD

**Issue by thomasmarkert** [oblomov-dev/abap2UI5#214]
Hey,

How to change the font size of elements?

- Input 
- Label
- List
- Table 
- Simple Form
- ...

I found this article for a Input Field.
https://answers.sap.com/questions/12883627/ui5-height-of-input-field.html

But I don't know how to implement that.

Best Regards
Thomas

**Comment by oblomov-dev** [comment]
@choper725 yes this is one option, i think you can overwrite the css with this in general for all apps. feel free to send a PR.

Another option is to write it directly into the xml-view, you can take a look at z2ui5_cl_app_demo_50. Took the example from 
https://answers.sap.com/questions/12883627/ui5-height-of-input-field.html

You have to write <html:style> like this:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/102328295/236635741-db98d311-9b85-4f5c-8283-95255dd3f2e2.png">

the css is then sent to the frontend with the view:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/102328295/236635787-2fdb39d6-784e-4e05-9488-4bf6c944a71a.png">

best regards

**Comment by thomasmarkert** [comment]
Excellent. You are the best. Thank you very much.
