### ISSUE TITLE
Error with 2 comboboxes

### ISSUE THREAD

**Issue by JKO-123** [oblomov-dev/abap2UI5#227]
Hi oblomov,

I get an error when I use a second combobox on the selection screen. I think in the method _create_binding in the loop over ms_db-t_attri, there must be a check if the name of the attribut is not numeric or if the bind_type is not ONE_TIME. With this change, it worked for me.

Regards Joerg

**Comment by oblomov-dev** [comment]
Ah yes thank you for the hint, i fixed it, now it is working:
<img width="1359" alt="image" src="https://github.com/oblomov-dev/abap2UI5/assets/102328295/cfc2f562-c2a6-4ccb-a707-7b7a21c0f609">

**Comment by oblomov-dev** [comment]
I close the issue. If you find a new error, just open a new issue.
