### ISSUE TITLE
SVG demo Z2UI5_CL_APP_DEMO_36 

### ISSUE THREAD

**Issue by nomssi** [oblomov-dev/abap2UI5#228]
Hi Oblomov-Dev,

I have an application that generates SVG and I would like to display it.
Can you please share how the SVG demo is supposed to look like? Is this correct?
![image](https://github.com/oblomov-dev/abap2UI5/assets/18452507/95fb9bbd-06db-4b37-8e14-62b730217b44)

**Comment by oblomov-dev** [comment]
Hi nomssi,
yes it is a very small demo, but the black rectangle is SVG. You can see it in the XML-View here:
<img width="916" alt="image" src="https://github.com/oblomov-dev/abap2UI5/assets/102328295/8272d56e-517f-4b46-aed9-bed1dca3ce73">
You can add in the same style more forms.
<rect width="100%" height="100%" />
Best regards.
