### ISSUE TITLE
Overflow Toolbar Toogle Button + Overflow Toolbar Menu Button in List Report

### ISSUE THREAD

**Issue by thomasmarkert** [oblomov-dev/abap2UI5#233]
Hi,
Is it possible Overflow Toolbar Toogle Button + Overflow Toolbar Menu Button to include a in the "Z2UI5_CL_APP_DEMO_49" example?

https://sapui5.hana.ondemand.com/#/entity/sap.m.OverflowToolbarToggleButton
https://sapui5.hana.ondemand.com/#/entity/sap.m.OverflowToolbarMenuButton

Best Regards
Thomas

**Comment by oblomov-dev** [comment]
I added these controls to demo z2ui5_cl_app_demo_06:
<img width="601" alt="image" src="https://github.com/oblomov-dev/abap2UI5/assets/102328295/bda0f7c2-37e9-4e3a-a27f-80a85c04cc7e">

you can add it to any other report in the same way as they work as normal aggregation controls for toolbars (will also add this to the list report with the next changes)

Best regards.

**Comment by thomasmarkert** [comment]
Thank you for the implementation.
