### ISSUE TITLE
spin the demos out to a dedicated repository

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [oblomov-dev/abap2UI5#236]
Would it be possible to move all the demos to a dedicated repository?

This way it would be possible to install the main library as a transportable package and the demos as local package, without moving them to testing and production.

**Comment by oblomov-dev** [comment]
good point! i will split demos from the rest and make a separated branch or repo.

**Comment by oblomov-dev** [comment]
The repository is now split up into two repositories and the demos are separated:
https://github.com/oblomov-dev

**Comment by AndreaBorgia-Abo** [comment]
Thanks, that was fast! :)
I added a quick comment in the community thread for this week challenge.

**Comment by oblomov-dev** [comment]
thanks for adding a comment, i close this issue now.
