### ISSUE TITLE
403 Forbidden - on Startup 

### ISSUE THREAD

**Issue by thomasmarkert** [oblomov-dev/abap2UI5#238]
Hi,

I get a 403 Forbidden message on startup. In the method z2ui5_cl_http_handler=>http_get there is a parameter CONTENT_SECURITY_POLICY.
Can it be because of that? Or how do I have to set the parameter?
![image](https://github.com/oblomov-dev/abap2UI5/assets/123086939/3136152b-c00f-42df-838f-725d857add1e)

Best Regards
Thomas

**Comment by oblomov-dev** [comment]
No the error with CONTENT_SECURITY_POLICY should not create this issue.

403 means an authorization problem. It should not be affected by CONTENT_SECURITY_POLICY.

In the beginning abap2UI5 is doing two calls, for the HTTP GET then the HTTP Post. Can you set an external breakpoint in your handler method and check if the HTTP Get method is called? Maybe then we see when this error happened.

**Comment by oblomov-dev** [comment]
Ok i overlooked something with the last update. The serveradress was wrong. Please pull one more time the actual version and try again.

**Comment by thomasmarkert** [comment]
It works. Thank you for your Help.
