### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by nomssi** [oblomov-dev/abap2UI5#242]
In Class Z2UI5_CL_HTTP_HANDLER, local class z2ui5_lcl_fw_handler,  METHOD set_app_start, the variable LV_TEST is always empty and the access to segment LV_TEST(11) is invalid => short dump => Internal Server Error
![image](https://github.com/oblomov-dev/abap2UI5/assets/18452507/d119d8ff-b711-4dd7-a1ef-54e0b3f2642e)

**Comment by oblomov-dev** [comment]
Hi Nomssi,

i needed to change the startup process and made another adjustment now. Can you try it again?

I am not sure if on_premise the behaviour of the following method is exactly like in abap-cloud or if same parameters are changing. Feel free to keep an eye on this methid:

```abap
  METHOD set_app_start.

    DATA lo_object TYPE REF TO object.

    result = NEW #( ).
    result->ms_db-id = z2ui5_lcl_utility=>get_uuid( ).

    DATA(lv_path_info) = z2ui5_lcl_utility=>get_header_val( '~path_info' ).
    SPLIT lv_path_info AT `?` INTO lv_path_info DATA(lv_dummy).
    SPLIT lv_path_info AT `/` INTO lv_path_info DATA(lv_dummy2).
    DATA(lv_classname) = z2ui5_lcl_utility=>get_trim_upper( lv_path_info ).

    IF lv_Classname IS INITIAL.
      result = result->set_app_system( ).
      RETURN.
    ENDIF.

    TRY.
        CREATE OBJECT result->ms_db-o_app TYPE (lv_classname).
        result->ms_db-o_app->id = result->ms_db-id.
        result->ms_db-t_attri   = z2ui5_lcl_utility=>get_t_attri_by_ref( result->ms_db-o_app ).
        RETURN.

      CATCH cx_root.
        result = result->set_app_system( error_text = `class with name ` && lv_classname && ` not found` ).
        RETURN.
    ENDTRY.

  ENDMETHOD.
```

**Comment by oblomov-dev** [comment]
Ah okay...

Can you give me the path of your http handler? Maybe something goes wrong there. My one is:
/sap/bc/http/sap/z_tb_dev_challenge_week2/

And it is working.

You can also check this position, there the link is created:
https://github.com/oblomov-dev/abap2UI5/blob/a024c6e52be0883f1407839aa865e6f9fe00f7ea/src/z2ui5_cl_http_handler.clas.locals_imp.abap#LL1056C38-L1056C38

In the end it should be: path/classname

**Comment by oblomov-dev** [comment]
The problem is i have no omprem so no chance to test it. But it would be nice when you can check in the following method the variable lv_path_info and lv_classname:
<img width="1410" alt="image" src="https://github.com/oblomov-dev/abap2UI5/assets/102328295/97ed0889-50ed-4365-a0fe-6737c818ea3c">
the url looks fine, so i am wondering why it does not create the app with the classname.

**Comment by nomssi** [comment]
I have another code for set_app_start( ). How come ?

the ~path_info header (e.g. /z2ui5_cl_app_demo_01) is not correctly parsed in my version

![image](https://github.com/oblomov-dev/abap2UI5/assets/18452507/d5baafeb-be6b-40be-8d6d-a3622ceda305)

**Comment by oblomov-dev** [comment]
Thank you for the info! I think the abap-cloud and abap-onprem behave slightly different here. You have an extra `/`, i changed the code again and added a shift left deleting leading `/`. Maybe you can check again?

**Comment by nomssi** [comment]
now I have an internal error "class with name /Z2UI5_CL_APP_DEMO_01 not found -", because the classname is /Z2UI5_CL_APP_DEMO_01.
The "SHIFT LEFT deleting" does change the path_info but not the class name.

**Comment by oblomov-dev** [comment]
Yes my fault, one more time!

**Comment by nomssi** [comment]
I can confirm it works now.
