### ISSUE TITLE
Bootstrapping configuration on ABAP Environment

### ISSUE THREAD

**Issue by ruthiel** [oblomov-dev/abap2UI5#245]
First of all, congratulations for this solution! 🥳 
It works great!!

Let me share my issue:
I've cloned and run ABAP2IU5 on my ABAP Environment (Cloud) and the development worked as expected!

However, **all my other application have now the SAP_HORIZON theme by default.**
I do not have GUI here, so I cannot go to the configuration of the bootstratping section.

Do you know how to revert the situation?
![image](https://github.com/oblomov-dev/abap2UI5/assets/17528112/033dd6cd-1bbe-4075-9376-1bcb2f6f8099)

**Comment by oblomov-dev** [comment]
Hi Ruthiel,

thank you for trying out abap2UI5 and your feedback.

Bootstrapping of abap2UI5 is independed to the other Fiori Elements apps of your system. So I am wondering about this behavior. There was an update last weekend to ABAP2305 of the abap cloud stack maybe the default theme changed to sap_horizon for the abap environment with that?

Maybe you can check it the other way around: Change the theme to sap_belize and check if the other apps in your system are still with the horizon theme or also changed:
```abap
    DATA(lt_config) = VALUE z2ui5_if_client=>ty_t_name_value(
        (  name = `data-sap-ui-theme`         value = `sap_belize` )
        (  name = `src`                       value = `https://sdk.openui5.org/resources/sap-ui-core.js` )
        (  name = `data-sap-ui-libs`          value = `sap.m` )
        (  name = `data-sap-ui-bindingSyntax` value = `complex` )
        (  name = `data-sap-ui-frameOptions`  value = `trusted` )
        (  name = `data-sap-ui-compatVersion` value = `edge` )
    ).

    z2ui5_cl_http_handler=>client = VALUE #(
      t_header = request->get_header_fields( )
      t_param  = request->get_form_fields( )
      body     = request->get_text( ) ).

    DATA(lv_resp) = SWITCH #( request->get_method( )
       WHEN 'GET'  THEN z2ui5_cl_http_handler=>http_get( EXPORTING t_config = lt_config )
       WHEN 'POST' THEN z2ui5_cl_http_handler=>http_post( ) ).
```

Best regards.

**Comment by ruthiel** [comment]
Hello @oblomov-dev !
Thanks for your quick answer!

I've tried exactly your solution after read all the documentation you've provided in SAP Blog.

I could modify the theme of the development where I'm using ABAP2UI5, but all others (list reports based on RAP) are being shown with SAP_HORIZON. I thought that it could reconfigure some standard table to the normal theme again, but it don't unfortunately.

I'm sure that the update didn't touched on this because some functionalities like editing a #fieldgroup are not working anymore.

I will keep trying to find some solution!

Thanks a lot for your help!
