### ISSUE TITLE
Syntac Error in CLAS Z2UI5_CL_APP_DEMO_53

### ISSUE THREAD

**Issue by thomasmarkert** [oblomov-dev/abap2UI5#246]
Hi,

it is a syntac error in the clas Z2UI5_CL_APP_DEMO_53.
![image](https://github.com/oblomov-dev/abap2UI5/assets/123086939/46987965-fc00-4423-807e-ff54e15f2805)

**Comment by oblomov-dev** [comment]
synchronized demos and main repo. should be fixed now.

**Comment by thomasmarkert** [comment]
It works.
