### ISSUE TITLE
Dynamic Page - Footer

### ISSUE THREAD

**Issue by axelmohnen** [oblomov-dev/abap2UI5#253]
Hi,
I can't add the dynamic page footer to the dynamic page.
Is this not support or do I missing something?
Error message:
![image](https://github.com/oblomov-dev/abap2UI5/assets/22371169/570a86bc-4e18-4925-a536-205986f07b44)

Thanks a lot.
Kind regards
Axel

**Comment by oblomov-dev** [comment]
Hi Axel, 

can you send me your xml definition? Looks like that you missed to add a specific control.

Best regards.

**Comment by oblomov-dev** [comment]
Hi Axel,

i updated main and the demos. You need to import also the namespace of the footer (which was not possible till now) when you use it with the dynamic page. I updated demo z2ui5_cl_app_demo_30:
<img width="500" alt="image" src="https://github.com/oblomov-dev/abap2UI5/assets/102328295/1bfad42e-dfa6-4d25-927c-3b6dd0f2d8f7">

```abap
     page->footer( ns = `f` )->overflow_toolbar(
             )->overflow_toolbar_button(
                 icon    = `sap-icon://edit`
                 text    = 'edit header'
                 type    = 'Emphasized'
                 tooltip = 'edit'
             )->overflow_toolbar_button(
                 icon    = `sap-icon://pull-down`
                 text    = 'show section'
                 type    = 'Emphasized'
                 tooltip = 'pull-down'
                 ).
```
You can try again.
Best regards.

**Comment by axelmohnen** [comment]
Yes, it works thanks a lot. Great job!
Only the <ToolbarSpacer/> is missing. I can't align the toolbar content to the right side.

**Comment by oblomov-dev** [comment]
Did you try to use the toolbar_spacer?
Something like this should bring the buttons to the right:
```abap
     page->footer( ns = `f` )->overflow_toolbar(
             )->toolbar_spacer( 
             )->overflow_toolbar_button(
                 icon    = `sap-icon://edit`
                 text    = 'edit header'
                 type    = 'Emphasized'
                 tooltip = 'edit'
             )->overflow_toolbar_button(
                 icon    = `sap-icon://pull-down`
                 text    = 'show section'
                 type    = 'Emphasized'
                 tooltip = 'pull-down'
                 ).
```

**Comment by axelmohnen** [comment]
Hi oblomov,
yes, toolbar_spacer() works perfectly!
Thanks a lot.
I will close the issue.
