### ISSUE TITLE
Logic changed?

### ISSUE THREAD

**Issue by nomssi** [oblomov-dev/abap2UI5#257]
It seems to me that the logic to parse the URL is not the same as in older version.

I think I used to start my application in class ZCL_AXAGE_WIZARD_UI with

http://vhcala4hci:50000/z2ui5demo?sap-client=001&app=ZCL_AXAGE_WIZARD_UI

but now it does not work. Luckily the initial page generates a valid link to the app, so I found out it should look like

http://vhcala4hci:50000/z2ui5demo/zcl_axage_wizard_ui?sap-client=001

Is it a feature?

best regards,
Jacques

**Comment by oblomov-dev** [comment]
Yes it is a feature. I changed the logic some weeks ago. Now the app is called with /server/path/classname.

That gives us some more freedom and the logic can be extended in the future to:
/server/path/classname/view
or
/server/path/classname/view/item

But did not finish this till now.
