### ISSUE TITLE
Best approach to embed/display graphics?

### ISSUE THREAD

**Issue by nomssi** [oblomov-dev/abap2UI5#260]
While playing with Developer Challenge (AXAGE Game Engine) I had the urge to display the rooms as fixed graphics. Those can be generated by DALL-E from a text prompt. But it is not straight forward how to include them in a game. 
The problem is uploading the data in a format that could be used by abapGit. How did you include you Oblomov picture in the demo layout?
Could a UI5 carousel like control be added to abap2UI5? 

best regards,
Jacques

**Comment by oblomov-dev** [comment]
Hi Nomssi,

I opened a separated issue to add the carousel control and i included the picture like this:
https://github.com/oblomov-dev/abap2UI5-demos/blob/main/src/z2ui5_cl_app_demo_17.clas.locals_imp.abap#L14

It is not a nice way but so far there is no abapgit compatible mime repository in "abap cloud". So the only way is to encode your picture to base64 and just put it into an abap string. (https://www.base64-image.de/)

Best regards.

**Comment by larshp** [comment]
steampunk doesnt have a mime repository, so its more a steampunk than abapgit problem

**Comment by oblomov-dev** [comment]
Oh yes of course, this is what i meant! No mime repository in steampunk (ABAP Cloud) and therefore also no chance for abapgit :/

**Comment by nomssi** [comment]
OK, thanks. I think I will adapt the class Z2UI5_CL_APP_DEMO_07 to generate and format the base64 data for ABAP. (delimiter + line length  etc..)

**Comment by nomssi** [comment]
I got it to work now...
![image](https://github.com/oblomov-dev/abap2UI5/assets/18452507/e7c01fe5-66c5-4277-8acd-5617cb323738)

**Comment by nomssi** [comment]
for the helper method to generate methods from image data, cf. to class Z2UI5_CL_APP_DEMO_BASE64 in the repository
https://github.com/nomssi/SAP-Developer-Code-Challenge

**Comment by oblomov-dev** [comment]
Wow! My approach looks very poor against this 😅
https://github.com/oblomov-dev/demo_abap2UI5-axage

Great work!
