### ISSUE TITLE
IF_HTTP_EXTENSION~HANDLE_REQUEST error

### ISSUE THREAD

**Issue by nk-cmd** [oblomov-dev/abap2UI5#262]
Hi, first of all many thanks and great respect for the project and this smart solution!

I have the following problem to compile the coding.

I created an Service (SICF)
I created an Class (SE24 with Name "Z2UI5_CL_HTTP_HANDLER" ) and inheritance from the interface "IF_HTTP_EXTENSION"

I copied the example Coding in the interface method

`  METHOD IF_HTTP_EXTENSION~HANDLE_REQUEST.

    DATA LT_HEADER TYPE TIHTTPNVP.
    SERVER->REQUEST->GET_HEADER_FIELDS( CHANGING FIELDS = LT_HEADER ).

    DATA LT_PARAM TYPE TIHTTPNVP.
    SERVER->REQUEST->GET_FORM_FIELDS( CHANGING FIELDS = LT_PARAM ).

    Z2UI5_CL_HTTP_HANDLER=>ClIENT = VALUE #(
       T_HEADER = LT_HEADER
       T_PARAM  = LT_PARAM
       BODY     = SERVER->REQUEST->GET_CDATA( ) ).

    DATA(LV_RESP) = SWITCH #( SERVER->REQUEST->GET_METHOD( )
       WHEN 'GET'  THEN Z2UI5_CL_HTTP_HANDLER=>HTTP_GET( )
       WHEN 'POST' THEN Z2UI5_CL_HTTP_HANDLER=>HTTP_POST( ) ).

    SERVER->RESPONSE->SET_CDATA( LV_RESP ).
    SERVER->RESPONSE->SET_STATUS( CODE = 200 REASON = 'success' ).
  ENDMETHOD.`

I got some compiler errors:

![image](https://github.com/oblomov-dev/abap2UI5/assets/62747555/09f95c9d-e7e6-492d-bcf6-f1bc66de2e61)

where is my mistake?

BR

**Comment by choper725** [comment]
what ABAP version are you on ? seems like below 7.4

**Comment by nk-cmd** [comment]
![image](https://github.com/oblomov-dev/abap2UI5/assets/62747555/bb1ac567-41e6-468e-8867-cc5fb1385b33)

**Comment by nomssi** [comment]
You created class z2ui5_cl_http_handler yourself? 
it is in the abapGit repository. You should create a class like Z2UI5_DEMO_HANDLER yourself.
