### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by nomssi** [oblomov-dev/abap2UI5#263]
From time to time (maybe up to once a day) I get a error in method  z2ui5_lcl_fw_db=>read( ),
![image](https://github.com/oblomov-dev/abap2UI5/assets/18452507/68d61e77-c046-4ab8-9781-12d9df9b3cfe)

 generated by the code

          z2ui5_lcl_utility=>raise( when = xsdbool( sy-subrc <> 0 ) ).

I am assuming the relevant draft table entry was purged from the draft table in the cleanup( ) method, as I can see only 2 entries: 
![image](https://github.com/oblomov-dev/abap2UI5/assets/18452507/564f7e1a-441c-45f4-864d-d5e67789fa64)

But I have no idea how to systematically reproduce the error.

**Comment by oblomov-dev** [comment]
Hi Nomssi,

thanks for sharing this issue. So far i don't have this problem, so i can just share some thoughts, maybe we get closer to the solution.

All entries in the draft table are deleted which are older than 4 hours:
<img width="523" alt="image" src="https://github.com/oblomov-dev/abap2UI5/assets/102328295/e30b5e7a-23d2-42bf-ae6c-962ad8efd67c">

I make this to keep the draft table small (and fast). So you will run into problems when you start an app then being inactive for 4 hours and the continue to work. But my guess is that after this time period you will get an auto logout from sap so you should never run into this problem. That there are only two entries means you have not been very active before the problem? Does your system have auto logout?

**Comment by larshp** [comment]
hmm, that code looks strange, if its 02:00:00, subtracting 4 hours gives 22:00:00, which is then earlier than 22 on the current day = everything?

suggest using https://abapedia.org/steampunk-2305-api/cl_abap_tstmp.clas.html for the timestamp calculation?

**Comment by oblomov-dev** [comment]
uhhh yes, you are right!

nice, cl_abap_tstmp exists on v.702:
<img width="380" alt="image" src="https://github.com/oblomov-dev/abap2UI5/assets/102328295/f0de9c6c-ceb3-46ae-b800-0a00f54c76c0">

I will make a correction!

**Comment by oblomov-dev** [comment]
This is the adjustment, time calculation should be more serious with this, will push it later to main.
<img width="500" alt="image" src="https://github.com/oblomov-dev/abap2UI5/assets/102328295/83f9f360-7ab5-4246-bf12-bd3cb1d61ea6">

**Comment by nomssi** [comment]
So it was a hidden feature between midnight and 4:00 am to send me to bed :)

**Comment by nomssi** [comment]
After implementing the fix, I had another case of this problem. This time, the app was left for about one hour and when I came back, the internal server error was triggered. This time they are 136 entries in the draft table. 

![image](https://github.com/oblomov-dev/abap2UI5/assets/18452507/721fcb32-daab-46bf-a592-818cfd9006e2)

![image](https://github.com/oblomov-dev/abap2UI5/assets/18452507/3f568e95-2480-4665-9d91-a16914a6bab0)

**Comment by oblomov-dev** [comment]
uhh i am really wondering. And the entry with the ID is not in the draft table?

Waiting for an hour is not so common (in abap cloud i get a timeout and auto-logout after 10 or 15 minutes) but it should work anyway because only draft entries older than 4 hours will now be deleted.

Will try to add better excpetions, maybe we can find out more.
