### ISSUE TITLE
Incompatible changes with commit #264 - new handling of additional event parameters

### ISSUE THREAD

**Issue by oblomov-dev** [oblomov-dev/abap2UI5#265]
The following commit creates an incompatibility:
https://github.com/oblomov-dev/abap2UI5/pull/264

The parameters event_data, event_data2, event_data2 are replaced with an importing table t_arg of type string table, so you need to adjust the methods:
_client->event
_client->get 

Check out the following demos:
https://github.com/oblomov-dev/abap2UI5-demos/blob/main/src/z2ui5_cl_app_demo_48.clas.abap
https://github.com/oblomov-dev/abap2UI5-demos/blob/main/src/z2ui5_cl_app_demo_52.clas.abap

@nomssi let me know if there are any problems. this solution is now more generic and shorter.

**Comment by nomssi** [comment]
@oblomov-dev I did not notice any problems with demos 48 and 52, but there is a syntay error in demo_57 on lower releases.

![image](https://github.com/oblomov-dev/abap2UI5/assets/18452507/83b941c9-7a88-4aed-b7b4-9062b427fe7c)

**Comment by oblomov-dev** [comment]
Thank you for the hint, i fixed it!
