### ISSUE TITLE
Submit a Form using the ENTER key

### ISSUE THREAD

**Issue by nomssi** [oblomov-dev/abap2UI5#266]
Hi Oblomov-dev,

I want to be able to capture the ENTER key of the user while inside a input and send the SimpleForm without having to click on a button. Well, it is easier to play adventure games that way :)

So I [checked](https://stackoverflow.com/questions/34454213/how-to-submit-a-sapui5-simpleform-using-the-enter-key) and there is `submit` parameter that is not used yet, so I propose to add the 'submit' event of the Input control to abap2UI5.

I have tried it and it seems to work:
- in method Z2UI5_CL_XML_VIEW->INPUT( ) adding the optional parameter "submit" 
- and extending the t_prop table definition with one line 

               ( n = `submit`           v = submit )

- adjusting the call 

             )->input(
                        showClearIcon   = abap_true
                        submit          = client->_event( `BUTTON_POST` )
                        value           = client->_bind( command )
                        placeholder     = 'enter your next command'

My first test was a success. Can you see any potential conflict with this approach?

best regards,

Jacques

**Comment by oblomov-dev** [comment]
Hi Jacques,

this is exactly the right way! Every control is a method and every importing parameter is a property.

So if you find an ui5 control you want to use, just add an extra method in the class Z2UI5_CL_XML_VIEW. And if you need an additional property just add an importing parameter.

Thank you for the PR this is a great help, i will merge it later.

Best regards.
