### ISSUE TITLE
Delete local variables?

### ISSUE THREAD

**Issue by nomssi** [oblomov-dev/ABAP2UI5#27]
In class Z2UI5_CL_HLP_TREE_XML Method WRITE( ), the DATA declarations

         mo_document TYPE REF TO if_ixml_document,
         mo_parser   TYPE REF TO if_ixml_parser_core,

overwrite attribute declaration for the same identifiers in the class. I guess it can be outright deleted?
I would appreciate if you could you provide some guidance on this.

regards,
Jacques

**Comment by oblomov-dev** [comment]
yes i think you can also just delete the whole class because it is not used somewhere else:
<img width="839" alt="image" src="https://user-images.githubusercontent.com/102328295/219715356-46bedabc-1ff4-4a6c-b4a3-2c5b20f648e3.png">

i forgot to clean this up after i switched to a simple method which is parsing the xml.

**Comment by oblomov-dev** [comment]
@nomssi i updated ABAP2UI5 now to a new versions. you have to do small changes to your apps to make them compatible to the new version, but then you have a lot more freedom and can build better apps ;)
if there are some problems with the on-prem compatibility with the new version, just let me know, that i can fix it.

**Comment by nomssi** [comment]
@oblomov-dev there are two errors I had to fix before getting this version to run:
![image](https://user-images.githubusercontent.com/18452507/220890450-57bd6503-c8ed-483f-a5f2-29a125ac9c2b.png)
1) Class Z2UI5_LCL_UTILITY Method TRANS_REF_TAB_2_TAB( )
you cannot dereference a field symbol in lower releases.
2) Class Z2UI5_LCL_UTILITY_TREE_JSON Method  GET_ATTRIBUTE( )
Exception CX_ABAP_API_STATE does not exist. I replaced it with CX_UCON_API_STATE but it should probably be more generic.

Thanks for the update

**Comment by nomssi** [comment]
My workaround for TRANS_REF_TAB_2_TAB does not work. It helps to compile and run many demos, but not  all.

**Comment by nomssi** [comment]
Here is an update:
![image](https://user-images.githubusercontent.com/18452507/220912198-0bc30ccf-fd06-4152-878f-7b4f5432f976.png)

**Comment by oblomov-dev** [comment]
Thanks a lot! 
i updated both now and comited it to the main branch.
The CX_UCON_API_STATE does not exist in cloud so i replaced it with a local exception. 
The coding change in the loop somehow does not update the value in the table, so the editable table function is not working. Therefore i needed to replace it with that:
<img width="615" alt="image" src="https://user-images.githubusercontent.com/102328295/220968979-e5fb8b07-a1be-49ee-b376-2ddbbd032e67.png">
Is  <comp> = lr_data_ui5->* compatible with your version?

**Comment by nomssi** [comment]
No, I get  the error:" A generic reference cannot be dereferenced (->) in the current statement."
A second field symbol is needed here, I got it to work with
![image](https://user-images.githubusercontent.com/18452507/221012219-69531e98-43ad-4138-8b61-d9860f3aea7d.png)

**Comment by oblomov-dev** [comment]
thanks a lot for your work @nomssi!!!
I merged your branch and made some other fixes. so far it works fine on my side. let me know if there are still any problems.

**Comment by nomssi** [comment]
Works for me thanks.
