### ISSUE TITLE
`NEW cl_abap_parallel( )->run_inst( )` and its types doesn't exist on NW 752 SP04

### ISSUE THREAD

**Issue by christianguenter2** [oblomov-dev/ABAP2UI5#31]
![grafik](https://user-images.githubusercontent.com/17437789/221111544-610c7ea8-787d-4173-a376-11fb4f407135.png)

**Comment by oblomov-dev** [comment]
ah yes thanks for the hint, i deleted it and it should work now.

**Comment by christianguenter2** [comment]
Thx.
