### ISSUE TITLE
`cl_abap_conv_codepage` doesn't exist on NW 752 SP04

### ISSUE THREAD

**Issue by christianguenter2** [oblomov-dev/ABAP2UI5#32]
![grafik](https://user-images.githubusercontent.com/17437789/221112196-5211ae7f-33db-4fc0-b089-9c62da7af120.png)

**Comment by oblomov-dev** [comment]
Great, very helpful, i replaced it, thanks!

**Comment by larshp** [comment]
https://github.com/oblomov-dev/ABAP2UI5/commit/a2f481dda5eab0e655865c4181ffd1dcc7a4ff09
