### ISSUE TITLE
`&&=` operator doesn't exist on NW 752 SP04

### ISSUE THREAD

**Issue by christianguenter2** [oblomov-dev/ABAP2UI5#33]
![grafik](https://user-images.githubusercontent.com/17437789/221113712-0f6413ae-9b1d-438e-8d15-e0730783dcf3.png)

**Comment by oblomov-dev** [comment]
@christianguenter2 thanks a lot for sending me this issues! i also fixed this one now.
Unfortunately i only have an abap cloud stack for testing at the moment, so no chance to find all on-premise problems. feel free to continue to send me all your problems, that i can try to fix this as soon as possible. would be nice making this project compatible to lower releases.

**Comment by larshp** [comment]
this is an issue that would be discovered by setting https://github.com/oblomov-dev/ABAP2UI5/blob/main/abaplint.jsonc#L13 to a version lower than 754

**Comment by oblomov-dev** [comment]
@larshp yes i checked it a few days ago with v750, but somehow i missed this 🤷‍♂️
@christianguenter2 thanks for your work, checked it and merged.

**Comment by christianguenter2** [comment]
Thx. Works now on 752 SP04. I'll check 750 later.
