### ISSUE TITLE
Field "NEW" is unknown.

### ISSUE THREAD

**Issue by sakirsek** [oblomov-dev/ABAP2UI5#35]
![issue](https://user-images.githubusercontent.com/26142915/221151870-e70ae2ab-cc14-40e7-9e1a-b0fc8447cb7f.jpg)

**Comment by oblomov-dev** [comment]
thanks for the hint! i fixed this, let me know if there are more problems. which abap release are you working with?

**Comment by larshp** [comment]
RAISE EXCEPTION NEW works from 752 and up, https://syntax.abaplint.org/?filter=raise#/abap/statement/Raise

**Comment by sakirsek** [comment]
> thanks for the hint! i fixed this, let me know if there are more problems. which abap release are you working with?

Thank you. 
I am working with version 7.51

**Comment by oblomov-dev** [comment]
@larshp somehow my v750 check also missed this. but now i checked it again with vscode and abalint, so far no more problems. but let's see if i really got all of them now 😅
