### ISSUE TITLE
CL_ABAP_CONTEXT_INFO doesnt exist in 750

### ISSUE THREAD

**Issue by sun-tassein** [oblomov-dev/ABAP2UI5#46]
Error in 750 system. Proposed fix is because cl_abap_context_info=>get_user_technical_name( ) actually calls cl_abap_syst=>get_user_name( ) and CL_ABAP_SYST is available in 750.
Error is in local definitions/implementations of z2ui5_cl_http_handler.

Error:
![image](https://user-images.githubusercontent.com/96750101/221438017-9d07e005-009c-4941-964e-07d8bc431ad3.png)

Proposed fix:
![image](https://user-images.githubusercontent.com/96750101/221438124-9b9e09ec-6698-46fc-af47-b1d19c60275d.png)

**Comment by oblomov-dev** [comment]
Thanks very much for the hint! i fixed it.
Changed it to sy-uname, because cl_abap_syst is not permitted in abap for cloud:
<img width="621" alt="image" src="https://user-images.githubusercontent.com/102328295/221439097-e9f2e331-dd66-436a-bb88-078050f59872.png">
you can try again.

**Comment by sun-tassein** [comment]
Thank you, it works.
