### ISSUE TITLE
Downport to ABAP syntax version v702

### ISSUE THREAD

**Issue by oblomov-dev** [oblomov-dev/abap2UI5#47]
Downport to ABAP syntax version v702, to make ABAP2UI5 compatible to a wide range of ABAP stacks.

**If there is someone with a v702 system who can test, after the downport, feel free to let me know!**

Project dependencies:
<img width="1328" alt="image" src="https://user-images.githubusercontent.com/102328295/222109430-f37c05f5-fdc7-4804-bfab-e52fd5056a39.png">
Syntax downport to-do:
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/102328295/222109730-a22d70b5-fe1a-4402-8564-0cbb7deb5c37.png">

**Comment by larshp** [comment]
https://rules.abaplint.org/downport/ can do a lot of it automatically, tried running it, need some bugs ironed out

**Comment by oblomov-dev** [comment]
yes thanks i will go with that! the only problem is that abaplint only checks for syntax and not if sap classes are used which not exist in a certain release. for example: https://github.com/oblomov-dev/ABAP2UI5/issues/46
abaplint with v750 did not warn. life is hard without a system in the sap world 😅

**Comment by larshp** [comment]
in the current configuration it knows https://github.com/oblomov-dev/ABAP2UI5/blob/main/abaplint.jsonc#L7 which has all the Steampunk objects, you can choose how much or little you want it to know

**Comment by oblomov-dev** [comment]
Adjusted the code, that it is ready to downport with abaplint without rework. All tests are succesfull now.
Thanks for the help, this topic is finished for now and in addition in a very elegant way! 👌
