### ISSUE TITLE
CMIS_STRING

### ISSUE THREAD

**Issue by larshp** [oblomov-dev/ABAP2UI5#51]
does not exist in 702
https://abapedia.org/steampunk-2302-api/cmis_string.dtel.html
just use the builtin type instead?

**Comment by oblomov-dev** [comment]
ah yes thanks, just fixed it:
<img width="494" alt="image" src="https://user-images.githubusercontent.com/102328295/221926585-f7897ee9-52e3-46e2-a831-feec61e7289f.png">
