### ISSUE TITLE
Switch Binding

### ISSUE THREAD

**Issue by sun-tassein** [oblomov-dev/ABAP2UI5#56]
I am not able to bind the switch value with the backend variable value.
I dont think it is working in the z2ui5_cl_app_demo_02 example either.

**Comment by oblomov-dev** [comment]
thanks for the hint, it's a bug! 
i fixed it and you can try it again. 
but don't forget to change the binding mode to this:
<img width="954" alt="image" src="https://user-images.githubusercontent.com/102328295/222652927-4dc2d8b8-aab1-4fc0-9858-a2c607a1f951.png">

**Comment by sun-tassein** [comment]
Thank you, it works now.
