### ISSUE TITLE
Downport and static code check

### ISSUE THREAD

**Issue by mbtools** [oblomov-dev/ABAP2UI5#6]
If you want to achieve a wider adoption, it should run lower SAP Basis releases as well. My suggestion would be to target 750 syntax. 

1. Install abaplint

https://github.com/apps/abaplint/installations/new

2. Give abaplint access to your repos 

https://github.com/settings/installations

3. Add abaplint.json to your repo

Get latest default from https://playground.abaplint.org (2nd tab) and put it in your root folder

Change the following:

```jsonc
  "syntax": {
    "version": "v750",
    //...
  }
```

With any commit, your repo will then be checked with the default rules. There will be many findings but no worry. If you don't like a rule, just set it to false. For example:

```jsonc
  "keep_single_parameter_on_one_line": false,
```

It takes a little time to find the rules you want to use and adjust code accordingly but it's worth the effort. It will keep things clean even if many other people contribute.

**Comment by oblomov-dev** [comment]
Yes that sounds very good! Due to the fact that the solution technically only needs a http handler, it makes sense making it compatible to older releases and 750 is a good target. I will check this when i finished my actual changes, thanks again for the information @mbtools!

**Comment by larshp** [comment]
also note the automatic https://rules.abaplint.org/downport/ rule, it always needs a few adjustments, but also works for a lot of scenarios
