### ISSUE TITLE
New (very stupid) question

### ISSUE THREAD

**Issue by PapaOurss** [oblomov-dev/ABAP2UI5#64]
Hello to all

I have followed the tutorial very conscientiously and implemented IF_HTTP_EXTENSION interface into class Z2UI5_CL_HTTP_HANDLER
![image](https://user-images.githubusercontent.com/126946203/222888505-ad33aa7e-fb6c-46f9-9efa-cd69dcdddd2c.png)

Then I moved to method IF_HTTP_EXTENSION~HANDLE_REQUEST to implement the snippet indicated in tutorial.
![image](https://user-images.githubusercontent.com/126946203/222889714-ac55a1af-864a-49b1-9702-a61bf79410ec.png)
![image](https://user-images.githubusercontent.com/126946203/222889964-5197b4e6-a704-4af4-b51c-1e447f2b1dcb.png)

It worked great ... but what do I have to do now ?
I have read carefully the initial blog and it just say that [When you are on an On-Premise system, you need to find the url by transaction SICF.](https://github.com/oblomov-dev/abap2ui5/wiki/Installation#2-start-the-abap2ui5-landing-page)

But where do I find the service ?

I warned you this was a very stupid one ...
Thousands thank you in advance for all your help.

Sebastien

**Comment by christianguenter2** [comment]
The service is called ZABAP2UI5. Right click on it press 'Test service'
![grafik](https://user-images.githubusercontent.com/17437789/222890248-43b42ab3-3a02-4662-ae15-c2f5549e2118.png)

**Comment by christianguenter2** [comment]
Instead of implementing `IF_HTTP_EXTENSION` in Z2UI5_CL_HTTP_HANDLER I'd create a new class instead as described here.
https://github.com/oblomov-dev/ABAP2UI5/wiki/First-App

**Comment by PapaOurss** [comment]
> The service is called ZABAP2UI5. Right click on it press 'Test service' ![grafik](https://user-images.githubusercontent.com/17437789/222890248-43b42ab3-3a02-4662-ae15-c2f5549e2118.png)

Service does not exist.
![image](https://user-images.githubusercontent.com/126946203/222891178-fe5ad58c-ecdf-43b2-84ae-b1e80f214862.png)

Does it means I need to create it as well ? Sorry for the question but it is not indicated in documentation.
Sebastien

**Comment by PapaOurss** [comment]
I created the service by myself and it works !

Now I just need to discuss with my administrators and decide if we should move to 7.50 or downgrade the ABAP code.

Tank you very much.
Topic closed

**Comment by christianguenter2** [comment]
Sorry, I forgot, that the service has to be created manually.

**Comment by christianguenter2** [comment]
" but it is not indicated in documentation", hm, I think it is:
https://github.com/oblomov-dev/abap2ui5/wiki/Installation#abap-standard

**Comment by oblomov-dev** [comment]
Thanks for trying this out @PapaOurss and @christianguenter2 for your help!

For a better understanding, I extended the documentation:
https://github.com/oblomov-dev/ABAP2UI5/wiki/Installation

@PapaOurss just keep on creating issues if you have problems or questions. I also plan to make ABAP2UI5 working on lower releases, i will let you know if i have any news concerning this.
