### ISSUE TITLE
How to configure ZABAP2UI5 ?

### ISSUE THREAD

**Issue by PapaOurss** [oblomov-dev/abap2UI5#66]
Hello Team

I am trying to build ZABAP2UI5 service in SICF but do not find documentation or tutorial to assist me.
Can somone share the setup ?

Here is what I did:

Service configuration
![image](https://user-images.githubusercontent.com/126946203/222896495-e7989b5f-3198-44bf-a920-cb5ed5af31bb.png)

GUI Configuration
![image](https://user-images.githubusercontent.com/126946203/222896444-77a2d53b-9cfa-4898-83df-476bb03320ee.png)

Handler configuration
![image](https://user-images.githubusercontent.com/126946203/222896530-b5c80424-3933-43b0-84e5-5faabbc00b64.png)

Any advice ?
Thank and regards
Sebastien

**Comment by oblomov-dev** [comment]
Thanks for trying this out! 
Normally you only have to put your handler class into the handler liste tab how you did. 

All the other options you can go with the default values. No need for any changes!

Go back to the tree view, right click on the service (ZABAP2UI5) and press "Test Service". Then the browser will start and you can see if there are any problems.

**Comment by PapaOurss** [comment]
Hi
If i remove all options, I can reach the ABAP2UI5 welcome page
![image](https://user-images.githubusercontent.com/126946203/222914154-960875a5-4376-4398-b920-5a9d685a4818.png)

But when I click on "Check", I get this error message
![image](https://user-images.githubusercontent.com/126946203/222914176-ab82e45c-2aac-4ea7-9a5b-80f4c5e0b1c4.png)

I guess this is linked to the fact that I am running with ABAP 7.40.
Or perhaps is there a link with my unsecured connection (not https).

**Comment by oblomov-dev** [comment]
OK the landing page is loaded, that means that the connection is right. it seems more like an internal abap problem.

Can you open the class z2ui5_cl_aoo_demo_01 in eclipse or se80 and check if you can activate it?
i guess that the specific class is not ready for 740 and some small syntax corrections are needed.

just send a screenshot of the activation problems.

**Comment by PapaOurss** [comment]
Hi @oblomov-dev 

Since version 702, service works fine with, as you said, no particular adjustment.
I will close this topic.

Thanks
Sebastien
