### ISSUE TITLE
Error Pull in Repository 

### ISSUE THREAD

**Issue by thomasmarkert** [oblomov-dev/abap2UI5#85]
Hello,

Error Message Pull in Repository:

![image](https://user-images.githubusercontent.com/123086939/224378455-defb0ae1-0942-436a-84aa-923646a3c825.png)

Great work. I am wating of the new Block 3/3 Demo App.

Best Regards
Thomas

**Comment by Ennowulff** [comment]
me too

`XML parser error: unexpected symbol; expected '<', ' Import of object $ABAP2UI5_00 failed File not found: z2ui5_if_app.intf.xml Import of object Z2UI5_IF_APP failed File not found: z2ui5_if_client.intf.xml Import of object Z2UI5_IF_CLIENT failed File not found: z2ui5_if_ui5_library.intf.xml Import of object Z2UI5_IF_UI5_LIBRARY failed File not found: z2ui5_t_draft.tabl.xml Import of object Z2UI5_T_DRAFT failed`

**Comment by larshp** [comment]
try setting a breakpoint here, https://github.com/abapGit/abapGit/blob/c8ef89d5fda2f7279e5f8cff71918ce23289c7f4/src/xml/zcl_abapgit_xml.clas.abap#L116

**Comment by larshp** [comment]
try setting a breakpoint here, https://github.com/abapGit/abapGit/blob/c8ef89d5fda2f7279e5f8cff71918ce23289c7f4/src/xml/zcl_abapgit_xml.clas.abap#L92

**Comment by oblomov-dev** [comment]
the description of the package 00 was not correct, i fixed it, should work now. can you try again?

**Comment by Ennowulff** [comment]
works fine! thanks a lot!

**Comment by Ennowulff** [comment]
ouch
![image](https://user-images.githubusercontent.com/75187288/224385191-ed691d96-949b-401c-9cb5-bc687b573fa6.png)

**Comment by larshp** [comment]
will probably have to extend the https://rules.abaplint.org/xml_consistency/ rule

**Comment by oblomov-dev** [comment]
yes a little bit embarrassing, thanks for pointing on this @Ennowulff  😅

i changed it manually on github, therefore the serialization of "&" was not correct i think, when abaplint takes care of this, that would be very nice!

**Comment by mbtools** [comment]
Might be better to use a workspace or vscode which can validate xml files (`&amp` would have worked as well)

**Comment by oblomov-dev** [comment]
yes... luckily this is open source, otherwise i have to spend a beer to you all for this mistake now. i better close this issue now ;)

**Comment by mbtools** [comment]
I take a beer anyway 🍺 😀
